version: 2.1

executors:
  ecmascript-leetcode:
    docker:
      - image: circleci/node:10
    working_directory: ~/ECMAScript-LeetCode

jobs:

  test:
    executor: ecmascript-leetcode
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Combat Preparation
          command: docker-compose up -d leetcode
      - run:
          name: Code Quality
          command: docker-compose exec leetcode yarn lint
      - run:
          name: Code Specification
          command: docker-compose exec leetcode yarn test
      - run:
          name: Code Coverage
          command: docker-compose exec leetcode yarn _codecov --token=$CODECOV_TOKEN

workflows:
  version: 2
  workflow:
    jobs:
      - test
