version: 2.1

executors:
  ecmascript-leetcode:
    docker:
      - image: circleci/node:14

jobs:
  test:
    executor: ecmascript-leetcode
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Combat Preparation
          command: docker-compose up -d leetcode
      # - run:
      #     name: Code Quality
      #     command: docker-compose exec leetcode npm run lint
      - run:
          name: Code Specification
          command: docker-compose exec leetcode npm test
      - run:
          name: Code Coverage
          command: docker-compose exec leetcode npm run coverage -- -t $CODECOV_TOKEN

workflows:
  version: 2
  workflow:
    jobs:
      - test
